version: "3.7"
services:
    db:
        image: postgres:latest
        container_name: db_postgres
        restart: always
        ports: 
            - 5432:5432
        environment:
            - POSTGRES_USER=appuser
            - POSTGRES_PASSWORD=pass123
            - POSTGRES_DB=cars-rental
        volumes:
            - pgdata:/data/postgres
    # app:
    #     build: .
    #     container_name: cars-rental
    #     ports: 
    #         - 3333:3333
    #     volumes:
    #         - .:/usr/app

volumes:
    pgdata:
        driver: local